@host = http://localhost:5194

POST {{host}}/product/create
Content-Type: application/json

{
    "productID": "DAM01",
    "productName": "Đầm đen",
    "category": "Đầm",
    "color": "Đen",
    "pattern": "",
    "sizeType": "letter",
    "quantities": [
        {
            "size": "S",
            "quantity": 10
        },
        {
            "size": "M",
            "quantity": 15
        },
        {
            "size": "L",
            "quantity": 12
        }
    ]
}

###
POST {{host}}/product/create
Content-Type: application/json

{
    "productID": "DAM02",
    "productName": "Đầm đỏ",
    "category": "Đầm",
    "color": "Đỏ",
    "pattern": "",
    "sizeType": "letter",
    "quantities": [
        {
            "size": "28",
            "quantities": 10
        },
        {
            "size": "30",
            "quantities": 15
        },
        {
            "size": "32",
            "quantities": 12
        }
    ]
}