@host = http://localhost:5194

###
GET {{host}}/product/pending
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYTU3NDJkNy1hM2E0LTQ2MzgtYTI0ZC03NmJlMDJiODUyOTMiLCJnaXZlbl9uYW1lIjoiSHXhu7NuaCBOZ-G7jWMgTmjGoW4iLCJqdGkiOiJmOTFhN2Q5Yi1lYTZiLTQzYzctYTIzYi1mOWE3MzI2NTJjN2QiLCJleHAiOjE3NzE0MTE5NzgsImlzcyI6IkNhcHN0b25lIiwiYXVkIjoiQ2Fwc3RvbmVVc2VycyJ9.ytuC_OCc0xDNo0FOUkV7aewtgUYNKpt4jv5dhdQZq1E

###
PATCH {{host}}/product/update/c48ffdbf-0e99-46f9-9f73-cd8c1ecb7f79
Content-Type: application/json

{
    "productID": "DAM01",
    "productName": "Đầm đen",
    "category": "Đầm",
    "color": "Đen",
    "pattern": "",
    "sizeType": "letter"
}