@host = http://localhost:5194

POST {{host}}/auth/register
Content-Type: application/json

{
    "FullName": "Do My Quyen",
    "Email": "test567@gmail.com",
    "Password": "123456"
}

### 
POST {{host}}/auth/login
Content-Type: application/json

{
    "Email": "test123@gmail.com",
    "Password": "123456"
}

###
GET {{host}}/auth/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYTU3NDJkNy1hM2E0LTQ2MzgtYTI0ZC03NmJlMDJiODUyOTMiLCJnaXZlbl9uYW1lIjoiSHV5bmggTmdvYyBOaG9uIiwianRpIjoiNTNlZDI4MWYtMmFlNS00YTBjLWE4YjUtN2U0OTY2YmJlZTk0IiwiZXhwIjoxNzcxMDEyNDU4LCJpc3MiOiJDYXBzdG9uZSIsImF1ZCI6IkNhcHN0b25lVXNlcnMifQ.iyKmvEVLgVwZnP1ngyof9T_F1qu90GUjFoI0_dRuGQo